Update remove_VCH_Disks.py
Fixed isVCH() method not to break if "Guest OS" value is null, returning this error message:
Traceback (most recent call last):
  File "remove_VCH_Disks.py", line 100, in <module>
    main()
  File "remove_VCH_Disks.py", line 70, in main
    if isVCH(child):
  File "remove_VCH_Disks.py", line 8, in isVCH
    if "Photon - VCH" in virtual_machine.summary.config.guestFullName:
TypeError: argument of type 'NoneType' is not iterable